/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BrowserMockup: typeof import('./src/components/BrowserMockup.vue')['default']
    ExtensionDemo: typeof import('./src/components/ExtensionDemo.vue')['default']
  }
}
